name: Deploy to staging by FTP

on:
  push:
    branches:
      - staging
      
  workflow_dispatch:

jobs:
  deploy-staging:
    name: Deploy staging
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v6

      - name: Check required secrets
        run: |
          if [ -z "${{ secrets.KIWEB_DEV_FTP_SERVER }}" ]; then echo "KIWEB_DEV_FTP_SERVER is EMPTY"; exit 1; else echo "KIWEB_DEV_FTP_SERVER is SET"; fi
          if [ -z "${{ secrets.KIWEB_DEV_FTP_USERNAME }}" ]; then echo "KIWEB_DEV_FTP_USERNAME is EMPTY"; exit 1; else echo "KIWEB_DEV_FTP_USERNAME is SET"; fi
          if [ -z "${{ secrets.KIWEB_DEV_FTP_PASSWORD }}" ]; then echo "KIWEB_DEV_FTP_PASSWORD is EMPTY"; exit 1; else echo "KIWEB_DEV_FTP_PASSWORD is SET"; fi
          if [ -z "${{ secrets.KIWEB_DEV_FTP_PORT }}" ]; then echo "KIWEB_DEV_FTP_PORT is EMPTY"; exit 1; else echo "KIWEB_DEV_FTP_PORT is SET"; fi
          if [ -z "${{ secrets.KIWEB_DEV_FTP_SERVER_DIR }}" ]; then echo "KIWEB_DEV_FTP_SERVER_DIR is EMPTY"; exit 1; else echo "KIWEB_DEV_FTP_SERVER_DIR is SET"; fi

      - name: Deploy to system-dev by FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.4.0
        with:
          server: ${{ secrets.KIWEB_DEV_FTP_SERVER }}
          username: ${{ secrets.KIWEB_DEV_FTP_USERNAME }}
          password: ${{ secrets.KIWEB_DEV_FTP_PASSWORD }}
          protocol: ftps
          port: ${{ secrets.KIWEB_DEV_FTP_PORT }}
          local-dir: ./
          server-dir: ${{ secrets.KIWEB_DEV_FTP_SERVER_DIR }}
          dry-run: true
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/.github/**
            **/.env
            **/teacher-auth/.env
            **/teacher-auth/vendor/**
            **/teacher-auth/private-pdfs/**
            **/private-pdfs/**
